# 注意：冒号后面要有一个空格

# 项目端口、上下文配置
server:
  port: 8081
  servlet:
    contextPath: /ddd_service

# 线程池配置
thread-pool:
  corePoolSize: 10
  maxPoolSize: 20
  keepAliveTime: 100
  blockQueueSize: 10

# http连接池
http-pool:
  maxTotal: 200

# 子域.功能
cluster:
  iam:
    enable: Y