# 注意：冒号后面要有一个空格

# 项目端口、上下文配置
server:
  port: 8081
  servlet:
    contextPath: /ddd_service

# 线程池配置
thread-pool:
  corePoolSize: 10
  maxPoolSize: 20
  keepAliveTime: 100
  blockQueueSize: 10

# http连接池
http-pool:
  maxTotal: 200

# 子域.功能
cluster:
  iam:
    enable: Y

lyn:
  rpc:
    # 总开关
    enable: true
    # server: 提供服务，client: 消费服务
    active:
       - client
       - server
    app-name: ddd_service
    register-address: 127.0.0.1:2181
    balancer: SmoothWeightRound
    usf: lyn-dev